/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.emfcloud.modelserver.coffee.model.coffee.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emfcloud.modelserver.coffee.model.coffee.BrewingUnit;
import org.eclipse.emfcloud.modelserver.coffee.model.coffee.CoffeePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Brewing Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BrewingUnitImpl extends ComponentImpl implements BrewingUnit
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BrewingUnitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CoffeePackage.Literals.BREWING_UNIT;
  }

} //BrewingUnitImpl
