/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.emfcloud.modelserver.coffee.model.coffee.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emfcloud.modelserver.coffee.model.coffee.CoffeePackage;
import org.eclipse.emfcloud.modelserver.coffee.model.coffee.DipTray;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dip Tray</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DipTrayImpl extends ComponentImpl implements DipTray
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DipTrayImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CoffeePackage.Literals.DIP_TRAY;
  }

} //DipTrayImpl
