/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.emfcloud.modelserver.coffee.model.coffee.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emfcloud.modelserver.coffee.model.coffee.CoffeePackage;
import org.eclipse.emfcloud.modelserver.coffee.model.coffee.WaterTank;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Water Tank</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WaterTankImpl extends ComponentImpl implements WaterTank
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WaterTankImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CoffeePackage.Literals.WATER_TANK;
  }

} //WaterTankImpl
