/**
 * generated by Xtext 2.19.0
 */
package org.eclipse.emfcloud.modelserver.coffee.model.coffee;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brewing Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emfcloud.modelserver.coffee.model.coffee.CoffeePackage#getBrewingUnit()
 * @model
 * @generated
 */
public interface BrewingUnit extends Component
{
} // BrewingUnit
